StringsDicts support
AckeeCZ/ACKLocalization pull request #16
Opened 2020-08-21 09:06 UTC by LukasHromadnik

In combination with SwiftGen 6.3 we are now able to support simple stringsDicts.

Currently we can handle only top level plurals. That means that nested plurals where multiple plural keys are used in one single translation key are not supported.

2020-08-21 11:16 UTC, olejnjak requested changes
I am also missing some tests regarding this feature 🤔

2020-08-21 11:16 UTC, olejnjak commented on Sources/ACKLocalizationCore/ACKLocalization.swift
> +            let pluralsPath = dirPath + "/Localizable.stringsDict"
As `Configuration` allows [customization of target strings file](https://github.com/AckeeCZ/ACKLocalization/blob/3b25965e4c6200e3613bda02bcfbfc1171ccdc3c/Sources/ACKLocalizationCore/Model/Configuration.swift#L42), I think that plurals strings dict should respect that as well.

2020-08-21 11:16 UTC, olejnjak commented on ACKLocalization.podspec
> +  s.version          = '1.1'
Generally I don't think that you should bump versions in such PRs.

2020-08-21 11:16 UTC, olejnjak commented on CHANGELOG.md
> +### 1.1
Generally I don't think that you should bump versions in such PRs.

2020-08-21 12:29 UTC, LukasHromadnik commented on Sources/ACKLocalizationCore/ACKLocalization.swift
> +            let pluralsPath = dirPath + "/Localizable.stringsDict"
I've added an item to the configuration with name for the stringsDict

2020-08-21 12:29 UTC, LukasHromadnik commented on ACKLocalization.podspec
> +  s.version          = '1.1'
reverted

2020-08-21 12:29 UTC, LukasHromadnik commented on CHANGELOG.md
> +### 1.1
reverted

2020-08-21 12:47 UTC, olejnjak reviewed
Well right now I think we're just missing the tests 🙂

2020-08-24 09:52 UTC, fortmarek reviewed
two minor comments, otherwise seems good, can't wait for this to land !

2020-08-24 09:52 UTC, fortmarek commented on Sources/ACKLocalizationCore/ACKLocalization.swift
> +            guard let pluralKeyRange = pattern.range(of: Constants.pluralKeyPattern, options: .regularExpression) else { assertionFailure(); return }
I think you can use IMHO nicer syntax `return assertionFailure`
also should not this throw an errror ? 🤔

2020-08-24 09:52 UTC, fortmarek commented on Sources/ACKLocalizationCore/ACKLocalization.swift
> +            guard let translationKey = PluralRuleKey(rawValue: pluralKey) else { assertionFailure(); return }
same comment as above

2020-08-24 10:13 UTC, olejnjak commented on Tests/ACKLocalizationCoreTests/ACKLocalization+Plurals.swift
> +class SheetsAPIServiceMock: SheetsAPIServicing {
just a nitpick, if `ACKLocalizationPluralsTests` is `final` I would also make this class final

2020-08-24 10:13 UTC, olejnjak commented on Tests/ACKLocalizationCoreTests/ACKLocalization+Plurals.swift
> +class AuthAPIServiceMock: AuthAPIServicing {
just a nitpick, if `ACKLocalizationPluralsTests` is `final` I would also make this class final

2020-08-24 12:03 UTC, LukasHromadnik commented
I made some changes to the plurals parser. Now we are able to determine if the translation key / plural key is missing, also all those checks throw an `PluralError` so the script won't complete until all plural keys are fine

2020-08-24 12:20 UTC, olejnjak approved these changes

2020-08-24 12:29 UTC, fortmarek commented on Sources/ACKLocalizationCore/Model/PluralError.swift
> +extension PluralError: Equatable {
`Equatable` should be automatically synthesized, shouldn't it?

2020-08-24 12:29 UTC, fortmarek commented on Tests/ACKLocalizationCoreTests/ACKLocalization+Plurals.swift
> +        XCTAssertThrowsError(try ackLocalization.buildPlurals(from: rows)) { error in
might be nice to add a following extension for `XCTest` (might be handy in the future, too): 
```swift
    func XCTAssertThrowsSpecific<Error: Swift.Error & Equatable, T>(_ closure: @autoclosure () throws -> T, _ error: Error, file: StaticString = #file, line: UInt = #line) {
        do {
            _ = try closure()
        } catch let closureError as Error {
            XCTAssertEqual(error, closureError, file: file, line: line)
        } catch let closureError {
            XCTFail("\(error) is not equal to: \(closureError)", file: file, line: line)
        }
    }
```

Your code can then be changed to something like this:
`XCTAssertThrowsSpecific(try ackLocalization.buildPlurals(from: rows), PluralError.missingTranslationkey(rows[0].key))`

2020-08-24 18:39 UTC, fortmarek approved these changes

2020-08-24 18:40 UTC, merged