Refactor string literal escaping
AckeeCZ/ACKLocalization pull request #24
Opened 2020-11-03 23:14 UTC by olejnjak

This PR refactors internal escaping sequences so the code is bit more readable.

We should probably discuss if the "added" tests should be present or not, I didn't want to change older tests so we can be sure we do not create any regression, but still wanted to test the new "syntax" as well. I think more tests even if they test the same thing do not hurt.

#### Checklist
- [x] Added tests (if applicable)

2020-11-04 08:34 UTC, janmisar requested changes
I think duplicated test are not necessary, it's just change of format, so I believe that 4 people's 👀  would catch the mistake if any.
If you want to keep old tests, feel free, no harm done of course, but please add a comment explaining why are there duplicated tests - could be pretty confusing in the future 😉

2020-11-06 06:08 UTC, LukasHromadnik commented
Why did you change only some of the tests? I thought that the we want to get rid of all the escaping hell

2020-11-06 14:04 UTC, LukasHromadnik approved these changes
Thanks for the update. 👍 amazing work!

2020-11-06 14:10 UTC, fortmarek approved these changes

2020-11-08 20:35 UTC, janmisar approved these changes

2020-11-08 20:38 UTC, merged